pub mod analyzer;
pub mod desktop;
pub mod detector;
pub mod diagnostics;
pub mod environment;
pub mod execution;
pub mod installer;
pub mod knowledge;
pub mod model;
pub mod observer;
pub mod paths;
pub mod planner;
pub mod progress;
pub mod registry;
pub mod runner;
pub mod strategy;
pub mod system;
pub mod umu;
pub mod umu_manager;
pub mod util;
pub mod vm;

pub const VERSION: &str = env!("CARGO_PKG_VERSION");
